{% set name = "rfsim" %}
{% set version = "0.0.2a4" %}
{% set sha256 = "2514c85534871f26c4e231e42ea438d21123fba75e9e1b3ae22177d09588fc16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
#  url: https://pypi.io/pypi/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/8f/d1/f80bb4d304dbab4d9d741fb89d87862489fe02fa834cf6e9ae5864d7296e/rfsim-0.0.2a4.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'
  detect_binary_files_with_prefix: True
  skip: True  # [(win and vc<14)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - numpy

  host:
    - python
    - pip
    - setuptools
    - {{ pin_compatible('numpy', max_pin='x.x.x') }}
    - configparser  # [py < 30]

  run:
    - python
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - sqlite
    - matplotlib
    - numpy
    - scipy
    - configparser  # [py < 30]

test:
  imports:
    - rfsim

about:
  home: https://github.com/thompsonsed/rfsim
  license: MIT
  license_file: LICENSE.txt
  summary: 'Toy simulator of rabbits and foxes'
  description: |
    Demonstration of how to link C++ to python
  doc_url: https://github.com/thompsonsed/rfsim
  dev_url: https://github.com/thompsonsed/rfsim

extra:
  recipe-maintainers:
    - thompsonsed
