{% set name = "rfsim" %}
{% set version = "0.0.2a3" %}
{% set sha256 = "01713a80b2559fe692865c466e91181e4cb910fac7d7665968ee90d2666dd98d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
#  url: https://pypi.io/pypi/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/d1/91/c0207ebc82c717fc9b1aa36f4632e94f70b708e7297c09092054fec4a865/rfsim-0.0.2a3.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'
  detect_binary_files_with_prefix: True
  skip: True  # [(win and vc<14)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - numpy

  host:
    - python
    - pip
    - setuptools
    - {{ pin_compatible('numpy', max_pin='x.x.x') }}
    - configparser  # [py < 30]

  run:
    - python
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - sqlite
    - matplotlib
    - numpy
    - scipy
    - configparser  # [py < 30]

test:
  imports:
    - rfsim

about:
  home: https://github.com/thompsonsed/rfsim
  license: MIT
  license_file: LICENSE.txt
  summary: 'Toy simulator of rabbits and foxes'
  description: |
    Demonstration of how to link C++ to python
  doc_url: https://github.com/thompsonsed/rfsim
  dev_url: https://github.com/thompsonsed/rfsim

extra:
  recipe-maintainers:
    - thompsonsed
